language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: 
           - lcov
         sources:
           - ubuntu-toolchain-r-test
    
install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v

jobs:
  include:
    - stage:
      name: "Build"
      script: mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DSTIXX_TESTS=OFF .. 
     - make
